---
title: "민주당 경선"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    logo: fig/minju_logo_section.png
    theme: readable
    css: css/minju.css
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
## 0. R 마크다운 환경설정 ------
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE,
                    comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
options(knitr.duplicate.label = 'allow')
## 0. R 팩키지 ------
library(flexdashboard)
library(tidyverse)
library(janitor)
library(extrafont)
loadfonts()
library(here)
library(fs)
library(glue)
library(gt)
library(plotly)

race_tbl <-
  read_rds(file = "data/race_tbl.rds")

electoral_college <- 
  read_rds(file = "data/electoral_college.rds")

sido_fct <- c("대전충남", "세종충북", "대구경북", "강원", "광주전남", "전북", "제주", "부울경", "인천", "경기", "서울")
report_day <- "10월 10일"
file_date <- "20211010"

gt_md <- glue::glue("기준 시점: 2021년 {report_day}")


candidate_tbl <- race_tbl %>% 
  group_by(후보자명) %>% 
  summarise(득표 = sum(득표)) %>% 
  mutate(득표율 = 득표 / sum(득표))

```




```{r child="dashboard/minju/graph.Rmd", encoding="UTF-8"} 
```

```{r child="dashboard/minju/table.Rmd", encoding="UTF-8"} 
```
