---
layout: page
title: "대통령 선거 2022년"
subtitle: "제19대 대통령 선거 결과"
author:
- name: "이광춘"
  affiliation: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
date: "`r Sys.Date()`"
tags: ["여론조사", "제20대", "대통령 선거", "후진국", "중진국", "선진국", "대통령 지지율", "모듈", "제18대"]
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: hide
    number_section: true
    self_contained: true
bibliography: bibliography_presid.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')
```

# 데이터 {#presid-18-data}

```{r presid-18-data}
library(tidyverse)
library(shiny)
library(gt)
library(gtExtras)

# 1. 데이터 ================================================================
## 1.1. 데이터 만들기
presid_17 <- krvotes::president_2017 %>%
  mutate(선거 = "2017년")

## 1.2. EDA 데이터 : 2017년 ================================================================

presid_17_tbl <- presid_17 %>%
  pivot_longer(문재인:김민찬, names_to = "후보", values_to = "득표") %>%
  select(-무표투표수, -기권수, -계)

gt_hubo_tlt <- presid_17_tbl %>%
  group_by(후보) %>%
  summarise(득표 = sum(득표)) %>%
  arrange(desc(득표)) %>%
  mutate(득표율 = 득표/sum(득표))

```

# 표 [^rmarkdown-dt] [^crosstalk-tutorial] {.tabset}

[^rmarkdown-dt]: ["Using crosstalk with DT in R Markdown" - This is a template for using the crosstalk with several grouped datatable widgets to create filterable reports in R Markdown (i.e. in a non-Shiny setting).](https://www.gerkelab.com/blog/2021/09/crosstalk-with-dt/)

[^crosstalk-tutorial]: [crosstalk Tutorial](https://emilyriederer.github.io/demo-crosstalk/tutorial/tutorial-rmd.html)

## 요약 {#presid-18-table-summary}

```{r presid-18-table}
## 2.1. 대선 후보 득표 (총계) ---------------------

presid_hubo_2017_gt <- gt_hubo_tlt %>%
  janitor::adorn_totals(name = "합계") %>%
  gt() %>%
  gt_theme_538() %>%
  tab_header(
    title = md("**&#x2600; 제19대 대통령 선거 &#x2600;**"),
    subtitle = md("*후보별 득표율 (2017년 5월 9일)*")
  ) %>%
  opt_align_table_header(align = "center") %>%
  tab_options(
    table.width = "300px",
    heading.background.color = "#1E61B0", # R logo 파란색
    heading.title.font.size = "20px",
    column_labels.background.color = "#F7F7F7", # R logo 회색
    column_labels.font.weight = "bold",
    stub.background.color = "#ffffff",
    stub.font.weight = "bold"
  ) %>%
  cols_align(
    align = "center",
    columns = `후보`
  ) %>%
  fmt_percent(
    columns = 득표율,
    decimals = 1,
    use_seps = FALSE
  ) %>%
  fmt_number(
    columns = 득표,
    decimals = 0,
    suffixing = FALSE
  ) %>%
  tab_style(style = list(cell_text(weight = 'bold',
                                   size  = "large",
                                   color = "blue")),
            locations = cells_body(columns = 후보,
                                   rows = 후보 == "문재인")) %>%
  tab_style(style = list(cell_text(weight = 'bold',
                                   size  = "large",
                                   color = "red")),
            locations = cells_body(columns = 후보,
                                   rows = 후보 == "홍준표")) %>%
  gt_highlight_rows(rows = 후보 == "문재인", font_weight = "bold", fill  = "#0388fc") %>%
  gt_highlight_rows(rows = 후보 == "홍준표", font_weight = "bold", fill  = "#ff6161") %>%
  gt_highlight_rows(rows = 후보 == "합계", font_weight = "bold", fill  = "gray90")

presid_hubo_2017_gt
```


## 시도 {#presid-18-data-sido-summary}

```{r presid-18-sido-table}
## 2.2. 대선 후보 득표 (시도) ---------------------

gt_sido_hubo_ttl <- presid_17_tbl %>%
  filter(str_detect(후보, pattern="문재인|안철수|홍준표|심상정|유승민")) %>%
  # mutate(후보 = factor(후보, levels = c("문재인", "홍준표", "안철수", "유승민", "심상정"))) %>%
  group_by(후보, 시도명) %>%
  summarise(득표 = sum(득표)) %>%
  arrange(desc(득표)) %>%
  group_by(시도명) %>%
  mutate(득표율 = 득표/sum(득표)) %>%
  mutate(득표 = scales::comma(득표),
           득표율 = scales::percent(득표율, accuracy = 1)) %>%
  mutate(득표종합 = glue::glue("{득표}<br>( {득표율} )")) %>%
  select(-득표, -득표율) %>%
  pivot_wider(names_from = "후보", values_from = "득표종합") %>%
  ungroup() %>%
  select(시도명, 문재인, 홍준표, 안철수, 유승민, 심상정)

## 합계 행 추가
gt_sido_ttl <- gt_hubo_tlt %>%
  filter(후보 %in% c("문재인", "홍준표", "안철수", "유승민", "심상정")) %>%
  mutate(득표율 = scales::percent(득표율, accuracy = 1)) %>%
  mutate(득표 = scales::comma(득표),
           득표종합 = glue::glue("{득표}<br>( {득표율} )")) %>%
  select(-득표, -득표율) %>%
  mutate(시도명 = "합계") %>%
  pivot_wider(names_from = "후보", values_from = "득표종합")


## GT 표작성
presid_hubo_sido_2017_gt <- gt_sido_hubo_ttl %>%
  bind_rows(gt_sido_ttl) %>%
  gt() %>%
  gt_theme_538() %>%
  tab_header(
    title = md("**&#x2600; 제19대 대통령 선거 &#x2600;**"),
    subtitle = md("*후보별 시도 득표율 (2017년 5월 9일)*")
  ) %>%
  opt_align_table_header(align = "center") %>%
  tab_options(
    table.width = "600px",
    heading.background.color = "#1E61B0", # R logo 파란색
    heading.title.font.size = "20px",
    column_labels.background.color = "#F7F7F7", # R logo 회색
    column_labels.font.weight = "bold",
    stub.background.color = "#ffffff",
    stub.font.weight = "bold"
  ) %>%
  fmt_markdown(columns = 문재인:심상정)  %>%
  cols_align(
    align = "center",
    columns = `시도명`
  ) %>%
  gt_highlight_cols(columns = 문재인, font_weight = "bold", fill  = "#0388fc") %>%
  gt_highlight_cols(columns = 홍준표, font_weight = "bold", fill  = "#ff6161") %>%
  cols_width(
    시도명 ~ px(100)
  )  %>%
  gt_highlight_rows(rows = 시도명 == "합계", font_weight = "bold", fill  = "gray90")


presid_hubo_sido_2017_gt
```

## 시군구 {#table-sigungu}



```{r presid-18-sigungu}
presid_17_sigungu_tbl <- presid_17_tbl %>% 
  filter(후보 %in% c("문재인", "홍준표", "안철수", "유승민", "심상정")) %>% 
  group_by(시도명, 구시군명, 후보) %>% 
  summarise(득표 = sum(득표)) %>% 
  unite("key", 시도명:구시군명, sep="_", remove = FALSE)
```



```{r crosstalk-sharddata}
library(crosstalk)
library(leaflet)
library(DT)

# Wrap data frame in SharedData
sigungu_sd <- SharedData$new(presid_17_sigungu_tbl, key = ~key)

# Use SharedData like a dataframe with Crosstalk-enabled widgets
bscols(
  widths = c(6, 6, 12),
  # Create a filter input
  crosstalk::filter_select(id = "sido", label = "시도", sharedData = sigungu_sd, multiple = FALSE,  group = ~시도명),
  crosstalk::filter_select("sigungu", "시군구명", sigungu_sd, multiple = FALSE, group = ~구시군명),

  datatable(sigungu_sd, extensions="Scroller", style="bootstrap", class="compact", width="100%",
    options=list(deferRender=TRUE, scrollY=300, scroller=TRUE))
)


```

