---
layout: page
title: "대통령 선거 2022년"
subtitle: "JTBC 차기대선주자"
author:
- name: "이광춘"
  affiliation: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
date: "`r Sys.Date()`"
tags: ["여론조사", "제20대", "대통령 선거", "후진국", "중진국", "선진국", "JTBC", "여론조사"]
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography_presid.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

```

# 차기 대선주자 {#jtbc-survey}

JTBC가 리얼미터에 2021-04-11 요청한 [여론조사결과 등록현황 상세보기](https://www.nesdc.go.kr/portal/bbs/B0000005/view.do?nttId=8509&menuNo=200467&searchTime=::%20%EB%82%A0%EC%A7%9C%EA%B5%AC%EB%B6%84%20::&sdate=&edate=&pdate=&pollGubuncd=VT019&searchCnd=2&searchWrd=jtbc&pageIndex=1)에 나온 데이터를 다운로드하자.

```{r first-page}
library(tidyverse)
library(magick)

download.file(url = "https://www.nesdc.go.kr/files/result/202107/FILE_202104120333254180.pdf.files/1.png", 
              destfile = "data/nesdc/jtbc/20210401/1.png", mode = "wb")

test_img <- image_read("data/nesdc/jtbc/20210401/1.png")

test_img %>% 
  image_resize("30%")
```


```{r}
library(rvest)

sample_html <- read_html("https://www.nesdc.go.kr/files/result/202107/FILE_202104120333254180.pdf.htm")

sample_html
  # html_nodes(xpath = '//*[@id="img-center-pane"]')
  # html_nodes(xpath = '//*[@id="page-area0"]')
  # html_nodes(css = '#page-area0')

```

# 차기대선 주사 선호도 [^1] {#page-main}

[^1]: https://statkclee.github.io/ingest-data/ocr-table.html

## 다운로드 {#page-main-download}

```{r main-page}

download.file(url = "https://www.nesdc.go.kr/files/result/202107/FILE_202104120333254180.pdf.files/6.png", 
              destfile = "data/nesdc/jtbc/20210401/6.png", mode = "wb")

main_img <- image_read("data/nesdc/jtbc/20210401/6.png")

main_img %>% 
  image_resize("100%")
```


## 이미지 전처리작업 {#page-main-preprocessing}

```{r preprocessing-page}
library(tesseract)

table_text <- tesseract::ocr_data("data/nesdc/jtbc/20210401/6.png", engine = "kor")
table_text %>% head(20)

main_processed_img <- main_img %>% 
  image_crop(geometry_area(x = 280, y = 125, 700, 820))   %>% 
  image_transparent("white", fuzz=10) %>% 
  image_background("white") %>%
  image_negate() %>%
  image_morphology(method = "Thinning", kernel = "Rectangle:20x1+0+0^<") %>%
  image_negate() 

main_processed_img
```

## 텍스트 추출 {#page-main-extract}

```{r extract-text-page}

whitelist <- glue::glue("1234567890")

table_text <- tesseract::ocr_data(main_processed_img, engine = tesseract(language = "eng",
                                  options = list(tessedit_char_whitelist = whitelist)))  

table_text %>% head(20)

```

## 칼럼 추출 {#page-main-extract-column}

```{r extract-column}
main_column_img <- main_img %>% 
  image_crop(geometry_area(x = 280, y = 125, 70, 820))   %>% 
  image_transparent("white", fuzz=5) %>% 
  image_background("white") %>%
  image_negate() %>%
  image_morphology(method = "Thinning", kernel = "Rectangle:20x1+0+0^<") %>%
  image_negate() 

main_column_img
```

```{r extract-column-data}
column_text <- tesseract::ocr_data(main_column_img, engine = tesseract(language = "eng",
                                  options = list(tessedit_char_whitelist = whitelist)))  

column_text
```

