---
layout: page
title: "대통령 선거 2022년"
subtitle: "제21대 국회의원"
author:
- name: "이광춘"
  affiliation: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
date: "`r Sys.Date()`"
tags: ["여론조사", "제20대", "대통령 선거", "후진국", "중진국", "선진국", "선거일정", "경선", "선거통계", "중앙선거여론조사", "2030", "국회의원", "제21대", "SNS"]
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: hide
    number_section: true
    self_contained: true
bibliography: bibliography_presid.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')
library(tidyverse)
library(rvest)
library(lubridate)
```

# 데이터 [^previous-crawling] {#congressman-data}

[^previous-crawling]: [데이터 가져오기 - 네이버 인물정보](https://statkclee.github.io/ingest-data/naver-people-info.html)

## 제 21 대 국회의원 위키백과 {#congressman-data-21}

```{r crawl-congressman-21, eval = FALSE}
# 0. 환경설정 -----
library(httr)
library(rvest)
library(tidyverse)
library(urltools)
library(glue)
library(extrafont)
loadfonts()

# 1. 국회의원 명단 -----
## 1.1. 긁어오기 -----
Sys.setlocale("LC_ALL", "C")

url <- "https://ko.wikipedia.org/wiki/대한민국_제21대_국회의원_목록_(지역구별)"

cm_list <- vector("list", length=19)

for(idx in 1:17) {
  cm_list[[idx]] <- url %>% 
    read_html() %>% 
    html_node(xpath = glue::glue('//*[@id="mw-content-text"]/div/table[{idx+1}]')) %>% 
    html_table(fill=TRUE) %>% 
    as_tibble()
}

Sys.setlocale("LC_ALL", "Korean")

for(idx in 1:17) {
  cm_list[[idx]] <- cm_list[[idx]] %>% 
    filter(str_detect(성명, pattern = "[가-힣]{2,4}"))
}

## 1.2. 시도별 국회의원 정보 -----
cm_list <- cm_list[1:17] 

sido_name <- c("서울특별시","부산광역시","대구광역시","인천광역시","광주광역시","대전광역시","울산광역시","세종특별자치시","경기도","강원도","충청북도","충청남도","전라북도","전라남도","경상북도","경상남도", "제주특별자치도")

names(cm_list) <- sido_name

## 2.3. 리스트 --> 데이터프레임 -----

name_v <- map(cm_list, "성명") %>% flatten %>% unlist %>% as.character()
precinct_v <- map(cm_list, "선거구명") %>% flatten %>% unlist %>% as.character()
party_v <- map(cm_list, "소속 정당") %>% flatten %>% unlist %>% as.character()
geo_v <- map(cm_list, "관할구역") %>% flatten %>% unlist %>% as.character()
num_v <- map(cm_list, "선수") %>% flatten %>% unlist %>% as.numeric()

cm_df <- tibble(시도   = rep(sido_name, map_int(cm_list, nrow)),
                선거구 = precinct_v,
                이름   = name_v, 
                정당   = party_v,
                지역   = geo_v,
                선수   = num_v)

# fs::dir_create("data/congressman")
# 
# cm_df %>%
#   write_rds("data/congressman/cm_df.rds")

# listviewer::jsonedit(cm_list)

```



```{r congressman-list-DT}
cm_tbl <- 
  read_rds("data/congressman/cm_df.rds")

DT::datatable(cm_tbl)
```



## 제 21 대 국회의원 국회DB {#congressman-data-21-DB}

자료출처: [제21대 국회의원 검색](https://open.assembly.go.kr/portal/assm/search/memberSchPage.do)

```{r congressman-db}
library(readxl)

electorates_raw <- read_excel("data/제21대_지역구.xlsx")

electorates_tbl <- electorates_raw %>% 
  mutate(시도명 = str_sub(지역, start =1, end =2))

proportion_raw <- read_excel("data/제21대_비례의원.xlsx")

proportion_tbl <- proportion_raw %>% 
  mutate(시도명 = str_sub(지역, start =1, end =2))

congressman <- bind_rows(proportion_tbl, electorates_tbl) %>% 
  select(-번호)

congressman %>% 
  DT::datatable()
```

# 네이버 인물정보 {#naver-info}

```{r naver-info}
# 1. 데이터: 네이버 인물정보 -----

## 1.1. 네이버 주소 -----

people_name <- "김병욱"

naver_url <- glue::glue("https://search.naver.com/search.naver?where=nexearch&sm=top_hty&fbm=1&ie=utf8&query={people_name}")

## 1.2. 네이버 인물정보 긁어오기 -----
### 사진정보 
pic_info <- read_html(naver_url) %>% 
  html_node(xpath = '//*[@id="main_pack"]/section[1]/div[1]/div[2]') %>% 
  html_node(css = 'img') %>% 
  html_attr('src')
  
pic_info_df <- tibble(key="사진", value=pic_info)

### 인물정보 ---------------------------------
key <- read_html(naver_url) %>% 
        html_node(xpath = '//*[@id="main_pack"]/section[1]/div[1]/div[2]') %>% 
        html_nodes('dt') %>% 
        html_text() %>% 
        as_tibble() %>% 
        rename(key=value)

value <- read_html(naver_url) %>% 
  html_node(xpath = '//*[@id="main_pack"]/section[1]/div[1]/div[2]') %>% 
  html_nodes('dd') %>% 
  html_text()

### SNS 서비스 ------------------------
info_nodes <- read_html(naver_url) %>% 
  html_node(xpath = '//*[@id="main_pack"]/section[1]/div[1]/div[2]') %>% 
  html_node(css = "dl")

#### SNS 서비스 이름
sns_name <- html_children(info_nodes) %>% 
  .[[4]] %>% 
  html_nodes("a") %>% 
  html_text()

#### SNS URL Links
sns_url <- html_children(info_nodes) %>% 
  .[[4]] %>% 
  html_nodes("a") %>% 
  html_attr("href")

sns_raw <- tibble(SNS = sns_name, 
                  link = sns_url)

sns_tbl <- tibble(key = "SNS",
                  value = sns_raw)

sns_raw %>% 
  nest()

### 데이터프레임 변환 -------------------------
p_info_tbl <- bind_cols(key=key, value=value) %>% 
  bind_rows(pic_info_df) %>% 
  pivot_wider(names_from = key, values_from = value) %>% 
  mutate(sns = sns_tbl)

DT::datatable(p_info_df)

```


