---
layout: page
title: "대통령 선거 2022년"
subtitle: "민주당 경선"
author:
- name: "이광춘"
  affiliation: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
date: "`r Sys.Date()`"
tags: ["여론조사", "제20대", "대통령 선거", "후진국", "중진국", "선진국", "선거일정", "경선", "주요", "민주당 경선"]
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: hide
    number_section: true
    self_contained: true
bibliography: bibliography_presid.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')
library(tidyverse)
library(rvest)
library(lubridate)
```

# 민주당 경선 데이터 {#minju-race}

[민주당 보도자료](https://theminjoo.kr/board/lists/presskit)를 통해서 제 20 대 대선 후보자 선출을 위한 민주당 경선 데이터를 얻을 수 있다.

- [210904_대전충남제20대_대선_후보자_선출_위한_결과_보도자료](data/minju_race/210904_대전충남제20대_대선_후보자_선출_위한_결과_보도자료.pdf)
- [210905_(세종충북)_제20대_대선_후보자_선출_위한_결과_보도자료](data/minju_race/210905_(세종충북)_제20대_대선_후보자_선출_위한_결과_보도자료_fn.pdf)
- [210911_대구경북_제20대_대선_후보자_선출_위한_결과_보도자료](data/minju_race/210911_대구경북_제20대_대선_후보자_선출_위한_결과_보도자료.pdf)
- [210912_제20대_대선후보자_선출_위한_순회경선_결과_보도자료(강원)](data/minju_race/210912_제20대_대선후보자_선출_위한_순회경선_결과_보도자료(강원)_fn.pdf)

```{r minju-data}
library(tidyverse)
library(tabulizer)

# locate_areas(file = "data/minju_race/210904.pdf", pages = 1)
# 선거인단
# Listening on http://127.0.0.1:4065
# [[1]]
#       top      left    bottom     right 
# 207.64360  58.57953 332.75103 538.15807 
# 경선결과
# [[1]]
#       top      left    bottom     right 
# 372.71591  55.10433 721.97417 538.15807 

# 대전충남_선거인단 <- extract_tables("data/minju_race/210904_대전충남제20대_대선_후보자_선출_위한_결과_보도자료.pdf",
대전충남_선거인단 <- extract_tables("data/minju_race/210904.pdf",
                             pages = 1,
                             encoding = "UTF-8",
                             method = "stream",
                             guess = TRUE,
                             area = list(c(207.64360,  58.57953, 332.75103, 538.15807)))

대전충남_선거결과 <- extract_tables("data/minju_race/210904.pdf",
                             pages = 1,
                             encoding = "UTF-8",
                             method = "stream",
                             guess = TRUE,
                             area = list(c(372.71591, 55.10433, 721.97417, 538.15807)))

```




