---
layout: page
title: "대통령 선거 2022년"
subtitle: "사진 배경 제거"
author:
- name: "이광춘"
  affiliation: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
date: "`r Sys.Date()`"
tags: ["여론조사", "제20대", "대통령 선거", "이재명", "윤석열", "이미지 배경", "제거"]
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography_presid.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

```

# 문제점 {#photo-ljm-problem}

## 사진속 인물 {#photo-ljm}

```{r image-magick-ljm}
library(tidyverse)
library(magick)

LJM <- image_read("fig/LJM_profile.jpg")

LJM_resized <- LJM %>% 
  image_resize("100")

LJM_resized
```

## 배경 사진 {#photo-ljm-background}

```{r image-magick-background}
road <- image_read("fig/road.jpg")

road_resized <- road %>% 
  image_resize("500")

road_resized
```


## 두 이미지 합성 {#combined-image} 

```{r image-composite}
road_resized %>% 
  image_composite(LJM_resized,
                  offset = "+400+200")
```

# 배경 투명하게 {#photo-ljm-transparent}

```{r backround-transparent}
LJM_tranparent <- LJM_resized %>% 
  image_transparent(color = "#EAEEF0")
```

```{r image-resized}
road_resized %>% 
  image_composite(LJM_tranparent,
                  offset = "+400+200")

```


# 마스킹 사례 {#masking} 

```{r dog-masking}
dog_img <- image_read_svg("http://www.supercoloring.com/sites/default/files/silhouettes/2015/05/cairn-terrier-black-silhouette.svg")

dog_transparent <- dog_img %>% 
  image_transparent('white')

image_append(c(dog_img %>% image_resize(200), 
               dog_transparent %>% image_resize(200),
               road_resized %>% image_resize(300)))
```


```{r dog-masking-in-action}
dog_img %>% 
  image_transparent('white') %>% 
  image_resize(300) %>% 
  image_composite(road_resized)
```

# 이미지 윤곽 {#image-borader}

```{r}
library(imager)

LJM_resized %>% 
  image_background("blue") %>% 
  image_border( color = "red")

LJM_imager <- magick2cimg(LJM_resized, alpha="flatten")

LJM_imager
```



