---
layout: page
title: "대통령 선거 2022년"
subtitle: "대선 시도 종합"
author:
- name: "이광춘"
  affiliation: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
date: "`r Sys.Date()`"
tags: ["여론조사", "제20대", "대통령 선거", "후진국", "중진국", "선진국", "선거일정", "경선"]
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: hide
    number_section: true
    self_contained: true
bibliography: bibliography_presid.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')
library(tidyverse)
library(rvest)
library(lubridate)
```

# 데이터 {#president-final}

중앙선거관리위원회 웹사이트에서 시도 데이터를 받아보자.

```{r president-data}
library(tidyverse)
library(rvest)
library(httr)


nec_20_url <- "http://info.nec.go.kr/electioninfo/electionInfo_report.xhtml?electionId=0020220309&requestURI=%2FWEB-INF%2Fjsp%2Felectioninfo%2F0020220309%2Fvc%2Fvccp09.jsp&topMenuId=VC&secondMenuId=VCCP09&menuId=VCCP09&statementId=VCCP09_%231&electionCode=1&cityCode=0&sggCityCode=0&townCode=-1&sggTownCode=0&x=94&y=25"

nec_20_html <- read_html(nec_20_url)

Sys.setlocale("LC_ALL", "C")

nec_20_raw <- nec_20_html %>% 
  html_elements(css = '.table01') %>% 
  html_table(fill = TRUE) %>% 
  .[[1]]

Sys.setlocale("LC_ALL", "Korean")


nec_20_tbl <- nec_20_raw %>% 
  janitor::clean_names(ascii = FALSE) %>% 
  set_names(c("시도명", "선거인수", "투표수", "이재명", "윤석열", "심상정", "오준호", "허경영", "이백윤", "옥은호", "김경재", "조원진", "김재연", "이경희", "김민찬", "계", "무효투표수", "기권수", "개표율")) %>% 
  slice(2:n()) %>% 
  filter(시도명 != "") %>% 
  pivot_longer(이재명:김민찬, names_to = "후보", values_to = "득표수") %>% 
  mutate(득표수 = parse_number(득표수)) %>%
  select(시도명, 후보, 득표수) %>% 
  filter(시도명 != "합계") 

nec_20_tbl
```


# 데이터 전처리

```{r tilemap-data}

nec_20_viz <- nec_20_tbl %>% 
  group_by(시도명) %>% 
  mutate(득표율 = 득표수 / sum(득표수) ) %>% 
  ungroup() %>% 
  filter(후보 %in% c("이재명", "윤석열")) %>% 
  ## 시각화를 위한 차이
  select(-득표수) %>% 
  pivot_wider(names_from = 후보, values_from = 득표율) %>% 
  mutate(차이 = 이재명 - 윤석열)

nec_20_viz

```


# 시각화

## 지도

```{r tilemap-sido-data}
library(sf)
sido_tilemap <- st_read("data/tilemap_sido/sido_hex_map_raw.shp")

sido_tilemap %>% 
  ggplot() +
    geom_sf(aes(geometry = geometry)) +
    theme_void()

```


## 지도 + 데이터

```{r tilemap-sido-matching}

sido_tilemap_sf <- sido_tilemap %>% 
  left_join(nec_20_viz, by = c("CTP_KOR_NM" = "시도명")) %>% 
  left_join(nesdc::sido_code, by = c("CTP_KOR_NM" = "시도명") ) %>% 
  mutate(label = glue::glue("{시도}\n{scales::percent(차이, accuracy =0.1)}"))

sido_tilemap_sf

```


## 시각화


```{r tilemap-sido-ggplot}

sido_tilemap_g <- sido_tilemap_sf %>% 
  ggplot() +
    geom_sf(aes(geometry = geometry, fill = 차이)) +
    theme_void(base_family = "NanumBarunpen") +
    geom_sf_text(aes(geometry = geometry, label = label),
                 size = 7,
                 fun.geometry = function(x) st_centroid(x)) +
    scale_fill_gradientn( colours = c("red", "white", "blue"), labels = scales::percent) +
    labs(
      title = "제20대 대통령선거 시도별 득표율 차이",
      subtitle = "득표율 차이: |이재명(47.83%) - 윤석열(48.56%)| =  0.73%",
      fill = "득표율 차이(%)",
      caption = "데이터출처: 중앙선거관리위원회 선거통계시스템"
    ) +
    theme(
      text = element_text(family = "NanumBarunpen"),
      plot.tag.position = c(0.85, .97),
      legend.position = "right",
      legend.title=element_text(size=15), 
      legend.key.size = unit(1.5, 'cm'),
      legend.text=element_text(size=13),
      plot.title=element_text(size=25, face="bold", family = "NanumBarunpen"),
      plot.subtitle=element_text(face="bold", size=17, colour="grey10", family = "NanumBarunpen"))   

sido_tilemap_g

ragg::agg_png("fig/sido_tilemap_g.png", width = 297, height = 210, units = "mm", res = 600, scaling = 0.85)
sido_tilemap_g
dev.off()



```


