---
title: "민주당 경선"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    logo: fig/minju_logo_section.png
    theme: readable
    css: css/minju.css
mainfont: NanumGothic 
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
## 0. R 마크다운 환경설정 ------
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE,
                    comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
options(knitr.duplicate.label = 'allow')
## 0. R 팩키지 ------
library(flexdashboard)
library(tidyverse)
library(janitor)
library(extrafont)
loadfonts()
library(here)
library(fs)
library(glue)
```


Overview
=================================================================================================

Row
-------------------------------------------------------------------------------

###  이재명

```{r minju-one}
ljm <- candidate_tbl %>% filter(후보자명 == "이재명") %>% pull(득표) %>% 
  scales::comma(.)
valueBox(ljm, caption = "이재명", icon = "fa-one", color = "#4287f5")
```

### 이낙연

```{r minju-four}
lny <- candidate_tbl %>% filter(후보자명 == "이낙연") %>% pull(득표) %>% 
  scales::comma(.)
valueBox(lny, caption = "이낙연", icon = "fa-four", color = "#f54242")
```

### 박용진 

```{r minju-five}
pyj <- candidate_tbl %>% filter(후보자명 == "박용진") %>% pull(득표) %>% 
  scales::comma(.)
valueBox(pyj, caption = "박용진", icon = "fa-five", color = "gray")
```

### 추미애 

```{r minju-six}
cma <- candidate_tbl %>% filter(후보자명 == "추미애") %>% pull(득표) %>% 
  scales::comma(.)
valueBox(cma, caption = "추미애", icon = "fa-six", color = "#42f578")
```



Column {.tabset}
-------------------------------------------------------------------------------

### Big Picture

