소셜 SNS
=================================================================================================


Column {.tabset .tabset-fade}
-------------------------------------------------------------------------------

### 뉴스

```{r social-news}
# wom_raw  <-  
#   read_rds(glue::glue("data/social/wom_raw_{Sys.Date() %>% str_remove_all('-')}.rds"))

wom_raw  <-  
  read_rds(glue::glue("data/social/wom_raw_20220303.rds"))

wom_news_g <- wom_raw %>% 
  filter(구분 == "뉴스") %>% 
  # mutate(구분 = factor(구분, levels = c("뉴스", "블로그", "커뮤니티", "유튜브", "인스타그램", "트위터"))) %>% 
  ggplot(aes(x = 날짜, y = 언급횟수, color = 후보, group = 후보,
             text = glue::glue("후보: {후보}\n",
                               "언급횟수: {scales::comma(언급횟수, accuracy = 1)}\n",
                               "날짜: {날짜}")) ) +
  geom_line() +
  geom_point(size = 0.7) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_date(date_labels = "%y년%m월") +
  theme_bw(base_family = "NanumBarunPen") +
  theme(legend.position = "top",
        legend.title=element_text(size=19), 
        legend.text=element_text(size=13),
        strip.text.x = element_text(size = rel(1.3), colour = "black", face="bold"),
        axis.text.y = element_text(size = rel(1.7), colour = "gray35", face="bold", 
                                   margin = margin(t = 0, r = 0, b = 0, l = 00)),
        axis.text.x = element_text(size = rel(1.3), colour = "black",  face="bold"),
        strip.background=element_rect(fill="gray95"),
        plot.title=element_text(size=25, face="bold", family = "NanumBarunpen"),
        plot.subtitle=element_text(face="bold", size=17, colour="grey10", family = "NanumBarunpen"))  +
  labs(x = "",
       y = "언급횟수/조회수",
       title = "SNS 트래픽 - 뉴스",
       subtitle = glue::glue("조사일자: 2022-01-01 ~ {wom_raw %>% filter(날짜 == max(날짜)) %>% pull(날짜)}"),
       caption = "데이터 출처: 썸트렌드") +
  scale_color_manual(values = c("이재명" = "blue", 
                                "윤석열" = "red", 
                                "안철수" = "#DE5020" ))  

ggplotly(wom_news_g, tooltip = "text")

```

### 블로그

```{r social-blog}

wom_blog_g <- wom_raw %>% 
  filter(구분 == "블로그") %>% 
  # mutate(구분 = factor(구분, levels = c("뉴스", "블로그", "커뮤니티", "유튜브", "인스타그램", "트위터"))) %>% 
  ggplot(aes(x = 날짜, y = 언급횟수, color = 후보, group = 후보,
             text = glue::glue("후보: {후보}\n",
                               "언급횟수: {scales::comma(언급횟수, accuracy = 1)}\n",
                               "날짜: {날짜}")) ) +
  geom_line() +
  geom_point(size = 0.7) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_date(date_labels = "%y년%m월") +
  theme_bw(base_family = "NanumBarunPen") +
  theme(legend.position = "top",
        legend.title=element_text(size=19), 
        legend.text=element_text(size=13),
        strip.text.x = element_text(size = rel(1.3), colour = "black", face="bold"),
        axis.text.y = element_text(size = rel(1.7), colour = "gray35", face="bold", 
                                   margin = margin(t = 0, r = 0, b = 0, l = 00)),
        axis.text.x = element_text(size = rel(1.3), colour = "black",  face="bold"),
        strip.background=element_rect(fill="gray95"),
        plot.title=element_text(size=25, face="bold", family = "NanumBarunpen"),
        plot.subtitle=element_text(face="bold", size=17, colour="grey10", family = "NanumBarunpen"))  +
  labs(x = "",
       y = "언급횟수/조회수",
       title = "SNS 트래픽 - 블로그",
       subtitle = glue::glue("조사일자: 2022-01-01 ~ {wom_raw %>% filter(날짜 == max(날짜)) %>% pull(날짜)}"),
       caption = "데이터 출처: 썸트렌드") +
  scale_color_manual(values = c("이재명" = "blue", 
                                "윤석열" = "red", 
                                "안철수" = "#DE5020" ))  

ggplotly(wom_blog_g, tooltip = "text")

```


### 커뮤니티

```{r social-community}

wom_community_g <- wom_raw %>% 
  filter(구분 == "커뮤니티") %>% 
  # mutate(구분 = factor(구분, levels = c("뉴스", "블로그", "커뮤니티", "유튜브", "인스타그램", "트위터"))) %>% 
  ggplot(aes(x = 날짜, y = 언급횟수, color = 후보, group = 후보,
             text = glue::glue("후보: {후보}\n",
                               "언급횟수: {scales::comma(언급횟수, accuracy = 1)}\n",
                               "날짜: {날짜}")) ) +
  geom_line() +
  geom_point(size = 0.7) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_date(date_labels = "%y년%m월") +
  theme_bw(base_family = "NanumBarunPen") +
  theme(legend.position = "top",
        legend.title=element_text(size=19), 
        legend.text=element_text(size=13),
        strip.text.x = element_text(size = rel(1.3), colour = "black", face="bold"),
        axis.text.y = element_text(size = rel(1.7), colour = "gray35", face="bold", 
                                   margin = margin(t = 0, r = 0, b = 0, l = 00)),
        axis.text.x = element_text(size = rel(1.3), colour = "black",  face="bold"),
        strip.background=element_rect(fill="gray95"),
        plot.title=element_text(size=25, face="bold", family = "NanumBarunpen"),
        plot.subtitle=element_text(face="bold", size=17, colour="grey10", family = "NanumBarunpen"))  +
  labs(x = "",
       y = "언급횟수/조회수",
       title = "SNS 트래픽 - 커뮤니티",
       subtitle = glue::glue("조사일자: 2022-01-01 ~ {wom_raw %>% filter(날짜 == max(날짜)) %>% pull(날짜)}"),
       caption = "데이터 출처: 썸트렌드") +
  scale_color_manual(values = c("이재명" = "blue", 
                                "윤석열" = "red", 
                                "안철수" = "#DE5020" ))  

ggplotly(wom_community_g, tooltip = "text")

```


### 인스타그램

```{r social-instagram}

wom_instagram_g <- wom_raw %>% 
  filter(구분 == "인스타그램") %>% 
  # mutate(구분 = factor(구분, levels = c("뉴스", "블로그", "커뮤니티", "유튜브", "인스타그램", "트위터"))) %>% 
  ggplot(aes(x = 날짜, y = 언급횟수, color = 후보, group = 후보,
             text = glue::glue("후보: {후보}\n",
                               "언급횟수: {scales::comma(언급횟수, accuracy = 1)}\n",
                               "날짜: {날짜}")) ) +
  geom_line() +
  geom_point(size = 0.7) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_date(date_labels = "%y년%m월") +
  theme_bw(base_family = "NanumBarunPen") +
  theme(legend.position = "top",
        legend.title=element_text(size=19), 
        legend.text=element_text(size=13),
        strip.text.x = element_text(size = rel(1.3), colour = "black", face="bold"),
        axis.text.y = element_text(size = rel(1.7), colour = "gray35", face="bold", 
                                   margin = margin(t = 0, r = 0, b = 0, l = 00)),
        axis.text.x = element_text(size = rel(1.3), colour = "black",  face="bold"),
        strip.background=element_rect(fill="gray95"),
        plot.title=element_text(size=25, face="bold", family = "NanumBarunpen"),
        plot.subtitle=element_text(face="bold", size=17, colour="grey10", family = "NanumBarunpen"))  +
  labs(x = "",
       y = "언급횟수/조회수",
       title = "SNS 트래픽 - 인스타그램",
       subtitle = glue::glue("조사일자: 2022-01-01 ~ {wom_raw %>% filter(날짜 == max(날짜)) %>% pull(날짜)}"),
       caption = "데이터 출처: 썸트렌드") +
  scale_color_manual(values = c("이재명" = "blue", 
                                "윤석열" = "red", 
                                "안철수" = "#DE5020" ))  

ggplotly(wom_instagram_g, tooltip = "text")

```

### 트위터

```{r social-twitter}

wom_twitter_g <- wom_raw %>% 
  filter(구분 == "트위터") %>% 
  # mutate(구분 = factor(구분, levels = c("뉴스", "블로그", "커뮤니티", "유튜브", "인스타그램", "트위터"))) %>% 
  ggplot(aes(x = 날짜, y = 언급횟수, color = 후보, group = 후보,
             text = glue::glue("후보: {후보}\n",
                               "언급횟수: {scales::comma(언급횟수, accuracy = 1)}\n",
                               "날짜: {날짜}")) ) +
  geom_line() +
  geom_point(size = 0.7) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_date(date_labels = "%y년%m월") +
  theme_bw(base_family = "NanumBarunPen") +
  theme(legend.position = "top",
        legend.title=element_text(size=19), 
        legend.text=element_text(size=13),
        strip.text.x = element_text(size = rel(1.3), colour = "black", face="bold"),
        axis.text.y = element_text(size = rel(1.7), colour = "gray35", face="bold", 
                                   margin = margin(t = 0, r = 0, b = 0, l = 00)),
        axis.text.x = element_text(size = rel(1.3), colour = "black",  face="bold"),
        strip.background=element_rect(fill="gray95"),
        plot.title=element_text(size=25, face="bold", family = "NanumBarunpen"),
        plot.subtitle=element_text(face="bold", size=17, colour="grey10", family = "NanumBarunpen"))  +
  labs(x = "",
       y = "언급횟수/조회수",
       title = "SNS 트래픽 - 트위터",
       subtitle = glue::glue("조사일자: 2022-01-01 ~ {wom_raw %>% filter(날짜 == max(날짜)) %>% pull(날짜)}"),
       caption = "데이터 출처: 썸트렌드") +
  scale_color_manual(values = c("이재명" = "blue", 
                                "윤석열" = "red", 
                                "안철수" = "#DE5020" ))  

ggplotly(wom_twitter_g, tooltip = "text")

```


### (전체) 유튜브

```{r yt-view}

# youtube_raw <- 
#   read_rds(glue::glue("data/social/youtube_raw_{Sys.Date() %>% str_remove_all('-')}.rds"))

youtube_raw <- 
  read_rds(glue::glue("data/social/youtube_raw_20220303.rds"))



yt_view_g <- youtube_raw %>% 
  filter(구분 == "조회수") %>% 
  ggplot(aes(x = 날짜, y = 언급횟수, color = 후보, group = 후보,
             text = glue::glue("후보: {후보}\n",
                               "언급횟수: {scales::comma(언급횟수, accuracy = 1)}\n",
                               "날짜: {날짜}")) ) +
    geom_line() +
    geom_point(size = 0.7) +
    scale_y_continuous(labels = scales::comma) +
    scale_x_date(date_labels = "%y년%m월") +
    theme_bw(base_family = "NanumBarunPen") +
    theme(legend.position = "top",
          legend.title=element_text(size=19), 
          legend.text=element_text(size=13),
          strip.text.x = element_text(size = rel(1.3), colour = "black", face="bold"),
          axis.text.y = element_text(size = rel(1.7), colour = "gray35", face="bold", 
                                     margin = margin(t = 0, r = 0, b = 0, l = 00)),
          axis.text.x = element_text(size = rel(1.3), colour = "black",  face="bold"),
          strip.background=element_rect(fill="gray95"),
          plot.title=element_text(size=25, face="bold", family = "NanumBarunpen"),
          plot.subtitle=element_text(face="bold", size=17, colour="grey10", family = "NanumBarunpen"))  +
    labs(x = "",
         y = "언급횟수/조회수",
         title = "(전체) 유튜브 - 조회수",
         subtitle = glue::glue("조사일자: 2022-01-01 ~ {wom_raw %>% filter(날짜 == max(날짜)) %>% pull(날짜)}"),
         caption = "데이터 출처: 썸트렌드") +
    scale_color_manual(values = c("이재명" = "blue", 
                                  "윤석열" = "red", 
                                  "안철수" = "#DE5020" ))  

ggplotly(yt_view_g, tooltip = "text")

```
