소셜 SNS 감성
=================================================================================================


Column {.tabset .tabset-fade}
-------------------------------------------------------------------------------

### 뉴스

```{r emotion-news}

emotion_social_raw <- 
  read_rds(glue::glue("data/social/emotion_social_raw_{Sys.Date() %>% str_remove_all('-')}.rds"))


emotion_news_g <- emotion_social_raw %>% 
  filter(채널 ==  "뉴스") %>% 
  ggplot(aes(x = 날짜, y = 긍부정횟수, color = 후보, group = 후보)) +
    geom_line() +
    geom_point(size = 0.7) +
    facet_grid(~구분, scale= "free_y") +
    scale_y_continuous(labels = scales::comma) +
    scale_x_date(date_labels = "%y년%m월") +
    theme_bw(base_family = "NanumBarunPen") +
    theme(legend.position = "top",
          legend.title=element_text(size=19), 
          legend.text=element_text(size=13),
          strip.text.x = element_text(size = rel(1.3), colour = "black", face="bold"),
          axis.text.y = element_text(size = rel(1.7), colour = "gray35", face="bold", 
                                     margin = margin(t = 0, r = 0, b = 0, l = 00)),
          axis.text.x = element_text(size = rel(1.3), colour = "black",  face="bold"),
          strip.background=element_rect(fill="gray95"),
          plot.title=element_text(size=25, face="bold", family = "NanumBarunpen"),
          plot.subtitle=element_text(face="bold", size=17, colour="grey10", family = "NanumBarunpen"))  +
  labs(x = "",
       y = "언급횟수/조회수",
       title = "소셜 SNS 감성 - 뉴스",
       subtitle = glue::glue("조사일자: 2022-01-01 ~ "),
       caption = "데이터 출처: 썸트렌드") +
  scale_color_manual(values = c("이재명" = "blue", 
                                "윤석열" = "red", 
                                "안철수" = "#DE5020" ))  

ggplotly(emotion_news_g)

```



### 커뮤니티

```{r emotion-community}

emotion_community_g <- emotion_social_raw %>% 
  filter(채널 ==  "커뮤니티") %>% 
  ggplot(aes(x = 날짜, y = 긍부정횟수, color = 후보, group = 후보)) +
    geom_line() +
    geom_point(size = 0.7) +
    facet_grid(~구분, scale= "free_y") +
    scale_y_continuous(labels = scales::comma) +
    scale_x_date(date_labels = "%y년%m월") +
    theme_bw(base_family = "NanumBarunPen") +
    theme(legend.position = "top",
          legend.title=element_text(size=19), 
          legend.text=element_text(size=13),
          strip.text.x = element_text(size = rel(1.3), colour = "black", face="bold"),
          axis.text.y = element_text(size = rel(1.7), colour = "gray35", face="bold", 
                                     margin = margin(t = 0, r = 0, b = 0, l = 00)),
          axis.text.x = element_text(size = rel(1.3), colour = "black",  face="bold"),
          strip.background=element_rect(fill="gray95"),
          plot.title=element_text(size=25, face="bold", family = "NanumBarunpen"),
          plot.subtitle=element_text(face="bold", size=17, colour="grey10", family = "NanumBarunpen"))  +
  labs(x = "",
       y = "언급횟수/조회수",
       title = "소셜 SNS 감성 - 커뮤니티",
       subtitle = glue::glue("조사일자: 2022-01-01 ~ "),
       caption = "데이터 출처: 썸트렌드") +
  scale_color_manual(values = c("이재명" = "blue", 
                                "윤석열" = "red", 
                                "안철수" = "#DE5020" ))  

ggplotly(emotion_community_g)

```


### 인스타그램

```{r emotion-instagram}

emotion_insta_g <- emotion_social_raw %>% 
  filter(채널 ==  "인스타") %>% 
  ggplot(aes(x = 날짜, y = 긍부정횟수, color = 후보, group = 후보)) +
    geom_line() +
    geom_point(size = 0.7) +
    facet_grid(~구분, scale= "free_y") +
    scale_y_continuous(labels = scales::comma) +
    scale_x_date(date_labels = "%y년%m월") +
    theme_bw(base_family = "NanumBarunPen") +
    theme(legend.position = "top",
          legend.title=element_text(size=19), 
          legend.text=element_text(size=13),
          strip.text.x = element_text(size = rel(1.3), colour = "black", face="bold"),
          axis.text.y = element_text(size = rel(1.7), colour = "gray35", face="bold", 
                                     margin = margin(t = 0, r = 0, b = 0, l = 00)),
          axis.text.x = element_text(size = rel(1.3), colour = "black",  face="bold"),
          strip.background=element_rect(fill="gray95"),
          plot.title=element_text(size=25, face="bold", family = "NanumBarunpen"),
          plot.subtitle=element_text(face="bold", size=17, colour="grey10", family = "NanumBarunpen"))  +
  labs(x = "",
       y = "언급횟수/조회수",
       title = "소셜 SNS 감성 - 인스타그램",
       subtitle = glue::glue("조사일자: 2022-01-01 ~ "),
       caption = "데이터 출처: 썸트렌드") +
  scale_color_manual(values = c("이재명" = "blue", 
                                "윤석열" = "red", 
                                "안철수" = "#DE5020" ))  

ggplotly(emotion_insta_g)

```

### 트위터

```{r emotion-twitter}

emotion_twitter_g <- emotion_social_raw %>% 
  filter(채널 ==  "트위터") %>% 
  ggplot(aes(x = 날짜, y = 긍부정횟수, color = 후보, group = 후보)) +
    geom_line() +
    geom_point(size = 0.7) +
    facet_grid(~구분, scale= "free_y") +
    scale_y_continuous(labels = scales::comma) +
    scale_x_date(date_labels = "%y년%m월") +
    theme_bw(base_family = "NanumBarunPen") +
    theme(legend.position = "top",
          legend.title=element_text(size=19), 
          legend.text=element_text(size=13),
          strip.text.x = element_text(size = rel(1.3), colour = "black", face="bold"),
          axis.text.y = element_text(size = rel(1.7), colour = "gray35", face="bold", 
                                     margin = margin(t = 0, r = 0, b = 0, l = 00)),
          axis.text.x = element_text(size = rel(1.3), colour = "black",  face="bold"),
          strip.background=element_rect(fill="gray95"),
          plot.title=element_text(size=25, face="bold", family = "NanumBarunpen"),
          plot.subtitle=element_text(face="bold", size=17, colour="grey10", family = "NanumBarunpen"))  +
  labs(x = "",
       y = "언급횟수/조회수",
       title = "소셜 SNS 감성 - 인스타그램",
       subtitle = glue::glue("조사일자: 2022-01-01 ~ "),
       caption = "데이터 출처: 썸트렌드") +
  scale_color_manual(values = c("이재명" = "blue", 
                                "윤석열" = "red", 
                                "안철수" = "#DE5020" ))  

ggplotly(emotion_twitter_g)

```


### 유튜브

```{r emotion-youtube}

emotion_youtube_raw <- 
  read_rds(glue::glue("data/social/emotion_youtube_raw_{Sys.Date() %>% str_remove_all('-')}.rds"))


emotion_youtube_g <- emotion_youtube_raw %>% 
  mutate(후보 = factor(후보, levels = c("이재명", "윤석열", "안철수"))) %>% 
  ggplot(aes(x = 날짜, y = 긍부정횟수, color = 후보, group = 후보)) +
    geom_line() +
    geom_point(size = 0.7) +
    facet_grid(~구분, scale= "free_y") +
    scale_y_continuous(labels = scales::comma) +
    scale_x_date(date_labels = "%y년%m월") +
    theme_bw(base_family = "NanumBarunPen") +
    theme(legend.position = "top",
          legend.title=element_text(size=19), 
          legend.text=element_text(size=13),
          strip.text.x = element_text(size = rel(1.3), colour = "black", face="bold"),
          axis.text.y = element_text(size = rel(1.7), colour = "gray35", face="bold", 
                                     margin = margin(t = 0, r = 0, b = 0, l = 00)),
          axis.text.x = element_text(size = rel(1.3), colour = "black",  face="bold"),
          strip.background=element_rect(fill="gray95"),
          plot.title=element_text(size=25, face="bold", family = "NanumBarunpen"),
          plot.subtitle=element_text(face="bold", size=17, colour="grey10", family = "NanumBarunpen"))  +
  labs(x = "",
       y = "언급횟수/조회수",
       title = "소셜 SNS 감성 - 유튜브",
       subtitle = glue::glue("조사일자: 2022-01-01 ~ "),
       caption = "데이터 출처: 썸트렌드") +
  scale_color_manual(values = c("이재명" = "blue", 
                                "윤석열" = "red", 
                                "안철수" = "#DE5020" ))  

ggplotly(emotion_youtube_g)

```

