---
output: html_document
editor_options: 
  chunk_output_type: console
---
검색어 추세
=================================================================================================


Column {.tabset .tabset-fade}
-------------------------------------------------------------------------------

### 구글 트렌드


```{r google-trends}

### 구글 트렌드 시각화 ------------------------------

hubo_raw <-
  read_rds(glue::glue('data/social/google_trends_20220308.rds'))

data_date <- hubo_raw$interest_over_time %>%
  mutate(date = lubridate::ymd(date)) %>%
  filter(date == max(date) -1) %>%
  pull(date) %>%
  unique()

google_trends_g <- hubo_raw$interest_over_time %>%
  as_tibble() %>%
  filter(str_detect(keyword, "이재명|윤석열|안철수|심상정")) %>%
  mutate(#date = lubridate::force_tz(date, tzone = "Asia/Seoul") %>% as.Date(),
    date = lubridate::ymd(date),
    keyword = factor(keyword, levels = c("이재명", "윤석열", "안철수", "심상정", "김건희")),
    hits = as.numeric(hits)) %>%
  rename(후보 = keyword) %>%
  filter(date != max(date)) %>%
  ggplot(aes(x = date, y = hits, color = 후보 )) +
    geom_point(show.legend = FALSE) +
    scale_size_continuous(range = c(0.5, 1.5)) +
    geom_line() +
    scale_x_date(date_labels = "%m월%d일", limits = c(as.Date("2022-1-01"), as.Date("2022-03-09"))) +
    theme_bw(base_family = "NanumBarunPen") +
    theme(legend.position = "top",
          legend.title=element_text(size=12),
          legend.text=element_text(size=10),
          strip.text.x = element_text(size = rel(1.3), colour = "black", family = "NanumMyeongjo", face="bold"),
          axis.text.y = element_text(size = rel(1.2), colour = "gray35", family = "NanumBarunpen", face="bold"),
          axis.text.x = element_text(size = rel(1.1), colour = "black", family = "NanumBarunpen", face="bold"),
          strip.background=element_rect(fill="gray95"),
          plot.title=element_text(size=25, face="bold", family = "NanumBarunpen"),
          plot.subtitle=element_text(face="bold", size=17, colour="grey10", family = "NanumBarunpen"))  +
    scale_color_manual(values = c("blue", "red", "#EA5505", "yellow", "black")) +
    labs(x = "",
         y = "검색수(hits)",
         title = "Google Trends 서비스",
         subtitle = glue::glue("지역: 대한민국, 시점: 2022년 01월 01일 ~ {format(data_date, '%Y년 %m월 %d일')}"),
         caption = "데이터 출처: 구글 트렌드 API, gtrendsR 패키지")  +
    geom_vline(xintercept = Sys.Date(), linetype="dashed", color = "black") +
    geom_vline(xintercept = as.Date("2022-03-09"), linetype="dashed", color = "black") +
    annotate("text", x = Sys.Date()-1.5, y = 99, label= glue::glue("현재:\n{format(Sys.Date(), '%m월%d일')}"),
             colour="black", size = 5, family = "NanumBarunpen")
    # annotate("text", x = as.Date("2022-03-09")-1.5, y = 99, label="선거일:\n 3월 9일", colour="black",
    #          size = 5, family = "NanumBarunpen")

ggplotly(google_trends_g)

```

### 네이버 검색어 트렌드

```{r naver-trends}
naver_json <- jsonlite::read_json("data/social/naver_20220308.json")

naver_tbl <- naver_json$results %>%
  enframe() %>%
  mutate(keyword = map_chr(value, "title")) %>%
  mutate(data = map(value, "data")) %>%
  unnest(data) %>%
  mutate(date = map_chr(data, "period"),
         ratio = map_dbl(data, "ratio")) %>%
  select(keyword, date, ratio)

naverdata_date <- naver_tbl %>%
  mutate(date = lubridate::ymd(date)) %>%
  filter(date == max(date)) %>%
  pull(date) %>% unique()

trend_naver_g <- naver_tbl %>%
  mutate(date = lubridate::ymd(date),
         keyword = factor(keyword, levels = c("이재명", "윤석열", "안철수", "심상정", "김건희"))) %>%
  rename(후보 = keyword) %>%
  ggplot(aes(x = date, y = ratio, color = 후보 )) +
    geom_point(show.legend = FALSE) +
    scale_size_continuous(range = c(0.5, 1.5)) +
    geom_line() +
    scale_x_date(date_labels = "%m월%d일") +
    theme_bw(base_family = "NanumBarunPen") +
    theme(legend.position = "top",
          legend.title=element_text(size=15),
          legend.text=element_text(size=13),
          strip.text.x = element_text(size = rel(1.3), colour = "black", family = "NanumMyeongjo", face="bold"),
          axis.text.y = element_text(size = rel(1.5), colour = "gray35", family = "NanumBarunpen", face="bold"),
          axis.text.x = element_text(size = rel(1.3), colour = "black", family = "NanumBarunpen", face="bold"),
          strip.background=element_rect(fill="gray95"),
          plot.title=element_text(size=18, face="bold", family = "NanumBarunpen"),
          plot.subtitle=element_text(face="bold", size=13, colour="grey10", family = "NanumBarunpen"))  +
    scale_color_manual(values = c("blue", "red", "#EA5505", "yellow", "black")) +
    labs(x = "",
         y = "검색수(hits)",
         title = "네이버 검색어 트렌드 서비스",
         subtitle = glue::glue("지역: 대한민국, 시점: 2022년 12월 01일 ~ {format(naverdata_date, '%Y년 %m월 %d일')}"),
         caption = "데이터 출처: 네이버 검색어 트렌드 API")   +
    geom_vline(xintercept = Sys.Date(), linetype="dashed", color = "black") +
    geom_vline(xintercept = as.Date("2022-03-09"), linetype="dashed", color = "black") +
    annotate("text", x = Sys.Date()-1, y = 99, label= glue::glue("현재:\n{format(Sys.Date(), '%m월%d일')}"),
             colour="black", size = 5, family = "NanumBarunpen") 
    # annotate("text", x = as.Date("2022-03-09")-1, y = 99, label="선거일:\n3월 9일",
    #          colour="black", size = 5, family = "NanumBarunpen")

ggplotly(trend_naver_g)
```
