---
output: html_document
editor_options: 
  chunk_output_type: console
---

후보채널 유튜브
=================================================================================================


Column {.tabset .tabset-fade}
-------------------------------------------------------------------------------

### 조회수

```{r youtube-view}

# candidate_video_raw <-
#   read_rds(glue::glue("data/social_youtube_raw_{Sys.Date() %>% str_remove_all('-')}.rds"))
candidate_video_raw <-
  read_rds(glue::glue("data/social/social_youtube_raw_20220308.rds"))

yt_stat <- candidate_video_raw %>%
  filter(후보명 != "안철수") %>% 
  select(data) %>%
  unnest(data)

yt_data_date <- yt_stat %>%
  mutate(게시일 = as.Date(publishedAt)) %>%
  filter(게시일 == max(게시일)) %>%
  pull(게시일) %>% unique()

youtube_view_g <- yt_stat %>%
  mutate(게시일 = as.Date(publishedAt)) %>%
  pivot_longer(조회수:댓글수) %>%
  mutate(value = as.numeric(value)) %>%
  mutate(후보명 = factor(후보명, levels = c("이재명", "윤석열", "심상정"))) %>%
  filter(name == "조회수") %>% 
  ggplot(aes(x=게시일, y= value, color = 후보명,
             text = glue::glue("후보명: {후보명}\n",
                               "조회수: {scales::comma(value, accuracy=1)}\n",
                               "동영상: {video_id}\n",
                               "게시일: {format(게시일, '%m월% %d일')}") )) +
    geom_jitter(size = 0.5) +
    geom_smooth(aes(group = 후보명, color = 후보명), se = FALSE, method = "loess", span = 0.75) +
    scale_x_date(date_labels = "%m월%d") +
    scale_y_sqrt(labels = scales::comma) +
    theme_bw(base_family = "NanumBarenPen") +
    scale_color_manual(values=c("blue", "red", "yellow")) +
    labs(x        = "",
         y        = "",
         title    = "대선 후보 유튜브 활동성 통계",
         subtitle = glue::glue("시점: 2022년 01월 01일 ~ {format(yt_data_date, '%Y년 %m월 %d일')}")) +
    theme_bw(base_family = "NanumBarunPen") +
    theme(legend.position = "top",
          legend.title=element_text(size=13),
          legend.text=element_text(size=11),
          strip.text.x = element_text(size = rel(1.2), colour = "black", family = "NanumMyeongjo", face="bold"),
          axis.text.y = element_text(size = rel(1.0), colour = "gray35", family = "NanumBarunpen", face="bold"),
          axis.text.x = element_text(size = rel(1.0), colour = "black", family = "NanumBarunpen", face="bold"),
          strip.background=element_rect(fill="gray95"),
          plot.title=element_text(size=18, face="bold", family = "NanumBarunpen"),
          plot.subtitle=element_text(face="bold", size=13, colour="grey10", family = "NanumBarunpen"))

ggplotly(youtube_view_g, tooltip = "text")


```


### 좋아요

```{r youtube-like}

youtube_like_g <- yt_stat %>%
  mutate(게시일 = as.Date(publishedAt)) %>%
  pivot_longer(조회수:댓글수) %>%
  mutate(value = as.numeric(value)) %>%
  mutate(후보명 = factor(후보명, levels = c("이재명", "윤석열", "심상정"))) %>%
  filter(name == "좋아요수") %>% 
  ggplot(aes(x=게시일, y= value, color = 후보명,
             text = glue::glue("후보명: {후보명}\n",
                               "좋아요수: {scales::comma(value, accuracy=1)}\n",
                               "동영상: {video_id}\n",
                               "게시일: {format(게시일, '%m월% %d일')}") )) +
    geom_jitter(size = 0.5) +
    geom_smooth(aes(group = 후보명, color = 후보명), se = FALSE, method = "loess", span = 0.75) +
    scale_x_date(date_labels = "%m월%d") +
    scale_y_sqrt(labels = scales::comma) +
    theme_bw(base_family = "NanumBarenPen") +
    scale_color_manual(values=c("blue", "red", "yellow")) +
    labs(x        = "",
         y        = "",
         title    = "대선 후보 유튜브 활동성 통계",
         subtitle = glue::glue("시점: 2022년 01월 01일 ~ {format(yt_data_date, '%Y년 %m월 %d일')}")) +
    theme_bw(base_family = "NanumBarunPen") +
    theme(legend.position = "top",
          legend.title=element_text(size=13),
          legend.text=element_text(size=11),
          strip.text.x = element_text(size = rel(1.2), colour = "black", family = "NanumMyeongjo", face="bold"),
          axis.text.y = element_text(size = rel(1.0), colour = "gray35", family = "NanumBarunpen", face="bold"),
          axis.text.x = element_text(size = rel(1.0), colour = "black", family = "NanumBarunpen", face="bold"),
          strip.background=element_rect(fill="gray95"),
          plot.title=element_text(size=18, face="bold", family = "NanumBarunpen"),
          plot.subtitle=element_text(face="bold", size=13, colour="grey10", family = "NanumBarunpen"))

ggplotly(youtube_like_g, tooltip = "text")
```

### 댓글수

```{r youtube-comment}

youtube_comment_g <- yt_stat %>%
  mutate(게시일 = as.Date(publishedAt)) %>%
  pivot_longer(조회수:댓글수) %>%
  mutate(value = as.numeric(value)) %>%
  mutate(후보명 = factor(후보명, levels = c("이재명", "윤석열", "심상정"))) %>%
  filter(name == "댓글수") %>% 
  ggplot(aes(x=게시일, y= value, color = 후보명,
             text = glue::glue("후보명: {후보명}\n",
                               "댓글수: {scales::comma(value, accuracy=1)}\n",
                               "동영상: {video_id}\n",
                               "게시일: {format(게시일, '%m월% %d일')}") )) +
    geom_jitter(size = 0.5) +
    geom_smooth(aes(group = 후보명, color = 후보명), se = FALSE, method = "loess", span = 0.75) +
    scale_x_date(date_labels = "%m월%d") +
    scale_y_sqrt(labels = scales::comma) +
    theme_bw(base_family = "NanumBarenPen") +
    scale_color_manual(values=c("blue", "red", "yellow")) +
    labs(x        = "",
         y        = "",
         title    = "대선 후보 유튜브 활동성 통계",
         subtitle = glue::glue("시점: 2022년 01월 01일 ~ {format(yt_data_date, '%Y년 %m월 %d일')}")) +
    theme_bw(base_family = "NanumBarunPen") +
    theme(legend.position = "top",
          legend.title=element_text(size=13),
          legend.text=element_text(size=11),
          strip.text.x = element_text(size = rel(1.2), colour = "black", family = "NanumMyeongjo", face="bold"),
          axis.text.y = element_text(size = rel(1.0), colour = "gray35", family = "NanumBarunpen", face="bold"),
          axis.text.x = element_text(size = rel(1.0), colour = "black", family = "NanumBarunpen", face="bold"),
          strip.background=element_rect(fill="gray95"),
          plot.title=element_text(size=18, face="bold", family = "NanumBarunpen"),
          plot.subtitle=element_text(face="bold", size=13, colour="grey10", family = "NanumBarunpen"))

ggplotly(youtube_comment_g, tooltip = "text")
```

